const games = [
  "Counter-Strike 2",
  "Dota 2",
  "PUBG: BATTLEGROUNDS",
  "R.E.P.O.",
  "Rust",
  "Monster Hunter Wilds",
  "Marvel Rivals",
  "Source SDK Base 2007",
  "Banana",
  "Tom Clancy's Rainbow Six Siege",
  "Grand Theft Auto V Legacy",
  "Apex Legends",
  "EA SPORTS FC 25",
  "War Thunder",
  "Warframe",
  "Grand Theft Auto V Enhanced",
  "Wallpaper Engine",
  "Spacewar",
  "Baldur's Gate 3",
  "Stardew Valley",
  "Crosshair X",
  "HELLDIVERS™ 2",
  "DayZ",
  "Football Manager 2024",
  "Team Fortress 2",
  "Hearts of Iron IV",
  "Call of Duty®",
  "Kingdom Come: Deliverance II",
  "Delta Force",
  "ELDEN RING",
  "Assassin's Creed Shadows",
  "Euro Truck Simulator 2",
  "FragPunk",
  "The Sims™ 4",
  "Dead by Daylight",
  "Crab Game",
  "Red Dead Redemption 2",
  "THRONE AND LIBERTY",
  "VRChat",
  "Destiny 2",
  "Soundpad",
  "Cyberpunk 2077",
  "Palworld",
  "Sid Meier's Civilization VI",
  "Valheim",
  "Terraria",
  "Overwatch® 2",
  "Split Fiction",
  "tModLoader",
  "Bongo Cat",
  "Path of Exile 2",
  "ARK: Survival Evolved",
  "Farming Simulator 25",
  "Project Zomboid",
  "7 Days to Die",
  "The Elder Scrolls V: Skyrim Special Edition",
  "Garry's Mod",
  "Rocket League",
  "NARAKA: BLADEPOINT",
  "The Binding of Isaac: Rebirth",
  "RimWorld",
  "Total War: WARHAMMER III",
  "Crusader Kings III",
  "Geometry Dash",
  "Balatro",
  "Satisfactory",
  "Left 4 Dead 2",
  "ARK: Survival Ascended",
  "BeamNG.drive",
  "THE FINALS",
  "Schedule I: Free Sample",
  "Don't Starve Together",
  "Age of Empires II: Definitive Edition",
  "Phasmophobia",
  "Factorio",
  "Squad",
  "Limbus Company",
  "Sons Of The Forest",
  "Battlefield™ 1",
  "Mount & Blade II: Bannerlord",
  "FINAL FANTASY XIV Online",
  "Once Human",
  "Black Desert",
  "Europa Universalis IV",
  "Path of Exile",
  "NBA 2K25",
  "Sid Meier's Civilization VII",
  "Sid Meier's Civilization V",
  "The Witcher 3: Wild Hunt",
  "Monster Hunter: World",
  "Yu-Gi-Oh! Master Duel",
  "Counter-Strike: Source",
  "SCUM",
  "Fallout 4",
  "Forza Horizon 5",
  "Counter-Strike",
  "Kingdom Come: Deliverance",
  "Assetto Corsa",
  "Lost Ark",
  "The Forest",
  "Unturned",
  "OBS Studio",
  "The Elder Scrolls Online",
  "Arma 3",
  "Hogwarts Legacy",
  "PAYDAY 2",
  "MIR4",
  "Cookie Clicker",
  "Hunt: Showdown 1896",
  "Conan Exiles",
  "The First Descendant",
  "Deadlock",
  "Legends of Idleon MMO",
  "STALCRAFT: X",
  "Stellaris",
  "Brawlhalla",
  "Arma Reforger",
  "Cities: Skylines",
  "Sea of Thieves",
  "eFootball™",
  "Anno 1800",
  "Fallout 76",
  "Enshrouded",
  "Raft",
  "Farming Simulator 22",
  "Slay the Spire",
  "Deep Rock Galactic",
  "Governor of Poker 3",
  "No Man's Sky",
  "Battlefield™ 2042",
  "Bloons TD 6",
  "Age of Empires IV: Anniversary Edition",
  "Street Fighter™ 6",
  "Albion Online",
  "It Takes Two",
  "The Isle",
  "Ready or Not",
  "Ghost of Tsushima DIRECTOR'S CUT",
  "Blender",
  "World of Tanks Blitz",
  "F1® 24",
  "Lethal Company",
  "Cities: Skylines II",
  "VTube Studio",
  "Lossless Scaling",
  "Russian Fishing 4",
  "Supermarket Together",
  "Elite Dangerous",
  "Black Myth: Wukong",
  "Warhammer 40,000: Space Marine 2",
  "Far Cry 5",
  "Hero Siege",
  "New World: Aeternum",
  "Battlefield™ V",
  "Ghost Recon Breakpoint",
  "Hollow Knight",
  "Hell Let Loose",
  "inZOI: Creative Studio",
  "Dark and Darker",
  "American Truck Simulator",
  "Soundpad Demo",
  "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
  "Risk of Rain 2",
  "Summoners War",
  "Diablo® IV",
  "Oxygen Not Included",
  "Two Point Museum",
  "MapleStory",
  "World of Tanks",
  "Supermarket Simulator",
  "EA SPORTS FC™ 24",
  "Core Keeper",
  "Myth of Empires",
  "Revolution Idle",
  "Magic: The Gathering Arena",
  "Undertale",
  "Tabletop Simulator",
  "Dying Light 2: Reloaded Edition",
  "Microsoft Flight Simulator",
  "Assassin's Creed Odyssey",
  "Dying Light",
  "YoloMouse",
  "SnowRunner",
  "Victoria 3",
  "Brotato",
  "Crosshair V2",
  "Eternal Return",
  "People Playground",
  "Resident Evil 4",
  "TEKKEN 8",
  "Call to Arms - Gates of Hell: Ostfront",
  "World of Warships",
  "Among Us",
  "Total War: ROME II - Emperor Edition",
  "DARK SOULS™ III",
  "Goose Goose Duck",
  "V Rising",
  "MONSTER HUNTER RISE",
  "SMITE 2",
  "ULTRAKILL",
  "Divinity: Original Sin 2",
  "DSX",
  "BLEACH Rebirth of Souls",
  "X4: Foundations",
  "FINAL FANTASY VII REBIRTH",
  "Melvor Idle",
  "Grounded",
  "Sekiro™: Shadows Die Twice",
  "Unnamed Space Idle",
  "MARVEL SNAP",
  "Aseprite",
  "Hades II",
  "SCP: Secret Laboratory",
  "Tom Clancy's The Division 2",
  "The Walking Dead: The Telltale Definitive Series",
  "Football Manager 2023",
  "Lust Goddess",
  "Need for Speed™ Heat",
  "Persona 5 Royal",
  "Age of Empires III: Definitive Edition",
  "Company of Heroes 3",
  "Subnautica",
  "Borderlands 3",
  "Kenshi",
  "Hades",
  "Warhammer 40,000: Darktide",
  "Space Engineers",
  "Pathfinder: Wrath of the Righteous - Enhanced Edition",
  "Guild Wars 2",
  "Atelier Yumia: The Alchemist of Memories & the Envisioned Land",
  "God of War Ragnarök",
  "Waifu",
  "Stumble Guys",
  "Palia",
  "STAR WARS™: The Old Republic™",
  "For Honor",
  "Forza Horizon 4",
  "Enlisted",
  "Aimlabs",
  "Rogue: Genesia",
  "Fields of Mistria",
  "DDNet",
  "Fallout: New Vegas",
  "DOOM",
  "Total War: MEDIEVAL II - Definitive Edition",
  "theHunter: Call of the Wild™",
  "Shop Titans",
  "Warhammer 40,000: Rogue Trader",
  "Disney Dreamlight Valley",
  "Foxhole"
];

export default games;